export const state = {
  macros: [],
  macroTree: { name: '宏', path: '宏', folders: [], files: [] },
  selectedMacro: null,
  editorRows: [],
  selectedActionPath: null,
  selectedLineKind: 'action',
  draggedActionPath: null,
  expandedLoopPathKeys: new Set(),
  inlineEditingPathKey: null,
  consoleLastId: 0,
  consoleLineCount: 0,
  currentTab: 'macro',
  showDebugParams: false,
  activeRecordPathInput: 'simplifyInput',
  runtimeProfile: {
    speed_factor: 1,
    random_enabled: false,
    random_min_ms: 0,
    random_max_ms: 0,
    low_cpu_enabled: false,
    low_cpu_time_period: true,
  },
  recordServiceRunning: false,
  recordHotkeys: {
    arm: 'f7',
    stop: 'f8',
    save: 'f9',
    clear: 'f10',
  },
  batchCommentMode: false,
  toastTimer: null,
  bootstrapDone: false,
  pollConsoleBusy: false,
  pollTimerId: null,
  snapshotTimerId: null,
  bindingTimerId: null,
  listenerTimerId: null,
  statusToastTs: {},
};
